### PR TITLE
Fixes #52: Change vercel deployment workflow to use ENV secrets as .env file

### LINKED ISSUE #52: Change vercel deployment workflow to use ENV secrets as .env file
the workflow is going to need to convert the secret to a base64 string to be able to create a .env file from it

### PR DESCRIPTION
**Pull request by redat97**
#52

### CODE REVIEW

**Comment by redat97** [comment]
I got mixed up and made my changes on the wrong branch I don't know if that's going to cause any issues

**Review by rngadam — APPROVED** [review]
Looks interesting and uses secret-envfile.

@ThomasCardin can you take this over?

**Comment by ThomasCardin** [comment]
> Looks interesting and uses secret-envfile.
> 
> @ThomasCardin can you take this over?

Yes, the issue is currently is the backlog

**Comment by ThomasCardin** [comment]
Closing this PR. We will preview deployment when this issue (https://github.com/ai-cfia/infra/issues/20) will be solved (iteration 3). No more maintenance time will be put into Vercel

**Pull request closed without merging**
